#pragma once

constexpr CLASS_ID CLSID_OBJECT_ACTOR			= TEXT2CLSID("O_ACTOR");
constexpr CLASS_ID CLSID_OBJECT_HLAMP			= TEXT2CLSID("O_HLAMP");
constexpr CLASS_ID CLSID_ENTITY					= TEXT2CLSID("ENTITY");
constexpr CLASS_ID CLSID_SPECTATOR				= TEXT2CLSID("SPECT");
constexpr CLASS_ID CLSID_OBJECT_PROJECTOR		= TEXT2CLSID("O_SEARCH");

// all the monsters
constexpr CLASS_ID CLSID_LEVEL_POINT			= TEXT2CLSID("LVLPOINT");
constexpr CLASS_ID CLSID_SCRIPT_OBJECT			= TEXT2CLSID("SCRPTOBJ");
constexpr CLASS_ID CLSID_AI_GRAPH				= TEXT2CLSID("AI_GRAPH");
constexpr CLASS_ID CLSID_AI_CROW				= TEXT2CLSID("AI_CROW");

constexpr CLASS_ID CLSID_AI_ZOMBIE				= TEXT2CLSID("AI_ZOM");
constexpr CLASS_ID CLSID_AI_POLTERGEIST			= TEXT2CLSID("AI_POLTR");

constexpr CLASS_ID CLSID_AI_FLESH				= TEXT2CLSID("AI_FLESH");
constexpr CLASS_ID CLSID_AI_FLESH_GROUP			= TEXT2CLSID("AI_FLE_G");

constexpr CLASS_ID CLSID_AI_PHANTOM				= TEXT2CLSID("AI_PHANT");
constexpr CLASS_ID CLSID_AI_SPONGER				= TEXT2CLSID("AI_SPONG");
constexpr CLASS_ID CLSID_AI_CONTROLLER			= TEXT2CLSID("AI_CONTR");
constexpr CLASS_ID CLSID_AI_BLOODSUCKER			= TEXT2CLSID("AI_BLOOD");
constexpr CLASS_ID CLSID_AI_STALKER				= TEXT2CLSID("AI_STL");
constexpr CLASS_ID CLSID_AI_BURER				= TEXT2CLSID("AI_BURER");
constexpr CLASS_ID CLSID_AI_GIANT				= TEXT2CLSID("AI_GIANT");
constexpr CLASS_ID CLSID_AI_CHIMERA				= TEXT2CLSID("AI_HIMER");
constexpr CLASS_ID CLSID_AI_FRACTURE			= TEXT2CLSID("AI_FRACT");
constexpr CLASS_ID CLSID_AI_DOG_BLACK			= TEXT2CLSID("AI_DOG_B");
constexpr CLASS_ID CLSID_AI_DOG_RED				= TEXT2CLSID("AI_DOG_R");
constexpr CLASS_ID CLSID_AI_DOG_PSY				= TEXT2CLSID("AI_DOG_P");
constexpr CLASS_ID CLSID_AI_DOG_PSY_PHANTOM		= TEXT2CLSID("AI_DOG_F");
constexpr CLASS_ID CLSID_AI_TRADER				= TEXT2CLSID("AI_TRADE");
constexpr CLASS_ID CLSID_AI_BOAR				= TEXT2CLSID("AI_BOAR");
constexpr CLASS_ID CLSID_AI_SNORK				= TEXT2CLSID("AI_SNORK");
constexpr CLASS_ID CLSID_AI_CAT					= TEXT2CLSID("AI_CAT");
constexpr CLASS_ID CLSID_AI_TUSHKANO			= TEXT2CLSID("AI_TUSH");
constexpr CLASS_ID CLSID_AI_RAT					= TEXT2CLSID("AI_RAT");

// vehicles
constexpr CLASS_ID CLSID_CAR					= TEXT2CLSID("C_NIVA");
constexpr CLASS_ID CLSID_VEHICLE_HELICOPTER		= TEXT2CLSID("C_HLCPTR");

constexpr CLASS_ID CLSID_EVENT					= TEXT2CLSID("EVENT");
constexpr CLASS_ID CLSID_OBJECT_FLYER			= TEXT2CLSID("O_FLYER");
constexpr CLASS_ID CLSID_OBJECT_DOOR			= TEXT2CLSID("O_DOOR");
constexpr CLASS_ID CLSID_OBJECT_LIFT			= TEXT2CLSID("O_LIFT");

// Artefacts
constexpr CLASS_ID CLSID_AF_MERCURY_BALL		= TEXT2CLSID("AF_MBALL");
constexpr CLASS_ID CLSID_AF_GRAVI				= TEXT2CLSID("AF_GRAVI");
constexpr CLASS_ID CLSID_AF_BLACKDROPS			= TEXT2CLSID("AF_BDROP");
constexpr CLASS_ID CLSID_AF_NEEDLES				= TEXT2CLSID("AF_NEEDL");
constexpr CLASS_ID CLSID_AF_BAST				= TEXT2CLSID("AF_BAST");
constexpr CLASS_ID CLSID_AF_BLACK_GRAVI			= TEXT2CLSID("AF_BGRAV");
constexpr CLASS_ID CLSID_AF_DUMMY				= TEXT2CLSID("AF_DUMMY");
constexpr CLASS_ID CLSID_AF_ZUDA				= TEXT2CLSID("AF_ZUDA");
constexpr CLASS_ID CLSID_AF_THORN				= TEXT2CLSID("AF_THORN");
constexpr CLASS_ID CLSID_AF_FADED_BALL			= TEXT2CLSID("AF_FBALL");
constexpr CLASS_ID CLSID_AF_ELECTRIC_BALL		= TEXT2CLSID("AF_EBALL");
constexpr CLASS_ID CLSID_AF_RUSTY_HAIR			= TEXT2CLSID("AF_RHAIR");
constexpr CLASS_ID CLSID_AF_GALANTINE			= TEXT2CLSID("AF_GALAN");
constexpr CLASS_ID CLSID_AF_CTA					= TEXT2CLSID("AF_CTA");

constexpr CLASS_ID CLSID_ARTEFACT				= TEXT2CLSID("ARTEFACT");

// Weapons
constexpr CLASS_ID CLSID_OBJECT_W_M134			= TEXT2CLSID("W_M134");
constexpr CLASS_ID CLSID_OBJECT_W_FN2000		= TEXT2CLSID("W_FN2000");
constexpr CLASS_ID CLSID_OBJECT_W_AK74			= TEXT2CLSID("W_AK74");
constexpr CLASS_ID CLSID_OBJECT_W_LR300			= TEXT2CLSID("W_LR300");
constexpr CLASS_ID CLSID_OBJECT_W_HPSA			= TEXT2CLSID("W_HPSA");
constexpr CLASS_ID CLSID_OBJECT_W_PM			= TEXT2CLSID("W_PM");
constexpr CLASS_ID CLSID_OBJECT_W_FORT			= TEXT2CLSID("W_FORT");
constexpr CLASS_ID CLSID_OBJECT_W_BINOCULAR		= TEXT2CLSID("W_BINOC");
constexpr CLASS_ID CLSID_OBJECT_W_SHOTGUN		= TEXT2CLSID("W_SHOTGN");
constexpr CLASS_ID CLSID_OBJECT_W_ASHOTGUN		= TEXT2CLSID("W_ASHTGN");
//  [8/15/2006]
constexpr CLASS_ID CLSID_OBJECT_W_MAGAZINED		= TEXT2CLSID("W_WMAGAZ");
//  [8/15/2006]
//  [8/17/2006]
constexpr CLASS_ID CLSID_OBJECT_W_MAGAZWGL		= TEXT2CLSID("W_WMAGGL");
//  [8/17/2006]
constexpr CLASS_ID CLSID_OBJECT_W_SVD			= TEXT2CLSID("W_SVD");
constexpr CLASS_ID CLSID_OBJECT_W_SVU			= TEXT2CLSID("W_SVU");
constexpr CLASS_ID CLSID_OBJECT_W_RPG7			= TEXT2CLSID("W_RPG7");
constexpr CLASS_ID CLSID_OBJECT_W_VAL			= TEXT2CLSID("W_VAL");
constexpr CLASS_ID CLSID_OBJECT_W_VINTOREZ		= TEXT2CLSID("W_VINT");
constexpr CLASS_ID CLSID_OBJECT_W_WALTHER		= TEXT2CLSID("W_WALTHR");
constexpr CLASS_ID CLSID_OBJECT_W_USP45			= TEXT2CLSID("W_USP45");
constexpr CLASS_ID CLSID_OBJECT_W_GROZA			= TEXT2CLSID("W_GROZA");
constexpr CLASS_ID CLSID_OBJECT_W_KNIFE			= TEXT2CLSID("W_KNIFE");
constexpr CLASS_ID CLSID_OBJECT_W_BM16			= TEXT2CLSID("W_BM16");
constexpr CLASS_ID CLSID_OBJECT_W_RG6			= TEXT2CLSID("W_RG6");

constexpr CLASS_ID CLSID_OBJECT_W_STATMGUN		= TEXT2CLSID("W_STMGUN");
// Weapons Ammo
constexpr CLASS_ID CLSID_OBJECT_AMMO			= TEXT2CLSID("AMMO");
//-----------------------------------------------------------------------------
constexpr CLASS_ID CLSID_OBJECT_A_VOG25			= TEXT2CLSID("A_VOG25");
constexpr CLASS_ID CLSID_OBJECT_A_OG7B			= TEXT2CLSID("A_OG7B");
constexpr CLASS_ID CLSID_OBJECT_A_M209			= TEXT2CLSID("A_M209");
//-----------------------------------------------------------------------------
// Weapons Add-ons
constexpr CLASS_ID CLSID_OBJECT_W_SCOPE			= TEXT2CLSID("W_SCOPE");
constexpr CLASS_ID CLSID_OBJECT_W_SILENCER		= TEXT2CLSID("W_SILENC");
constexpr CLASS_ID CLSID_OBJECT_W_GLAUNCHER		= TEXT2CLSID("W_GLAUNC");
constexpr CLASS_ID CLSID_OBJECT_W_MAGAZINE		= TEXT2CLSID("W_MAGAZN");

// Modifiers
constexpr CLASS_ID CLSID_OBJECT_M_QDAMAGE		= TEXT2CLSID("O_QDMG");
constexpr CLASS_ID CLSID_OBJECT_M_IMMORTAL		= TEXT2CLSID("O_IMMORT");
constexpr CLASS_ID CLSID_OBJECT_M_INVIS			= TEXT2CLSID("O_INVIS");

constexpr CLASS_ID CLSID_OBJECT_HEALTH			= TEXT2CLSID("O_HEALTH");
constexpr CLASS_ID CLSID_OBJECT_ARMOR			= TEXT2CLSID("O_ARMOR");

constexpr CLASS_ID CLSID_OBJECT_TRIGGER			= TEXT2CLSID("O_TRIGER");

// Targets
constexpr CLASS_ID CLSID_TARGET					= TEXT2CLSID("T_BASE");
constexpr CLASS_ID CLSID_TARGET_ASSAULT			= TEXT2CLSID("T_ASS");
constexpr CLASS_ID CLSID_TARGET_CS_BASE			= TEXT2CLSID("T_CSBASE");
constexpr CLASS_ID CLSID_TARGET_CS				= TEXT2CLSID("T_CS");
constexpr CLASS_ID CLSID_TARGET_CS_CASK			= TEXT2CLSID("T_CSCASK");

// Standard level object
constexpr CLASS_ID CLSID_OBJECT_ITEM_STD		= TEXT2CLSID("O_ITEM");
constexpr CLASS_ID CLSID_OBJECT_BREAKABLE		= TEXT2CLSID("O_BRKBL");
constexpr CLASS_ID CLSID_OBJECT_CLIMABLE		= TEXT2CLSID("O_CLMBL");
constexpr CLASS_ID CLSID_OBJECT_HOLDER_ENT		= TEXT2CLSID("O_HLDR_E");
//
constexpr CLASS_ID CLSID_PH_SKELETON_OBJECT		= TEXT2CLSID("P_SKELET");
constexpr CLASS_ID CLSID_OBJECT_PHYSIC			= TEXT2CLSID("O_PHYSIC");
constexpr CLASS_ID CLSID_PHYSICS_DESTROYABLE	= TEXT2CLSID("P_DSTRBL");
constexpr CLASS_ID CLSID_INVENTORY_BOX			= TEXT2CLSID("O_INVBOX");

// Zones 
constexpr CLASS_ID CLSID_ZONE					= TEXT2CLSID("Z_ZONE");
constexpr CLASS_ID CLSID_Z_MBALD				= TEXT2CLSID("Z_MBALD");
constexpr CLASS_ID CLSID_Z_MINCER				= TEXT2CLSID("Z_MINCER");
constexpr CLASS_ID CLSID_Z_ACIDF 				= TEXT2CLSID("Z_ACIDF");
constexpr CLASS_ID CLSID_Z_GALANT				= TEXT2CLSID("Z_GALANT");
constexpr CLASS_ID CLSID_Z_RADIO				= TEXT2CLSID("Z_RADIO");
constexpr CLASS_ID CLSID_Z_BFUZZ				= TEXT2CLSID("Z_BFUZZ");
constexpr CLASS_ID CLSID_Z_RUSTYH				= TEXT2CLSID("Z_RUSTYH");
constexpr CLASS_ID CLSID_Z_AMEBA				= TEXT2CLSID("Z_AMEBA");
constexpr CLASS_ID CLSID_Z_NOGRAVITY			= TEXT2CLSID("Z_NOGRAV");
constexpr CLASS_ID CLSID_Z_FRYUP  				= TEXT2CLSID("Z_FRYUP");
constexpr CLASS_ID CLSID_Z_DEAD  				= TEXT2CLSID("Z_DEAD");
constexpr CLASS_ID CLSID_LEVEL_CHANGER			= TEXT2CLSID("LVLCHNGR");
constexpr CLASS_ID CLSID_SCRIPT_ZONE			= TEXT2CLSID("SCRIPTZN");
constexpr CLASS_ID CLSID_Z_TEAM_BASE  			= TEXT2CLSID("Z_TEAMBS");
constexpr CLASS_ID CLSID_Z_TORRID  				= TEXT2CLSID("Z_TORRID");
constexpr CLASS_ID CLSID_SPACE_RESTRICTOR 		= TEXT2CLSID("SPACE_RS");
constexpr CLASS_ID CLSID_SMART_ZONE				= TEXT2CLSID("SMRTZONE");
constexpr CLASS_ID CLSID_Z_CAMPFIRE				= TEXT2CLSID("Z_CFIRE");

// Detectors
constexpr CLASS_ID CLSID_DETECTOR_SIMPLE		= TEXT2CLSID("D_SIMDET");
constexpr CLASS_ID CLSID_DETECTOR_ADVANCED		= TEXT2CLSID("D_ADVANC");
constexpr CLASS_ID CLSID_DETECTOR_ELITE			= TEXT2CLSID("D_ELITE");
constexpr CLASS_ID CLSID_DETECTOR_SCIENTIFIC	= TEXT2CLSID("D_SCIENT");

// PDA
constexpr CLASS_ID CLSID_DEVICE_PDA				= TEXT2CLSID("D_PDA");

// Devices
constexpr CLASS_ID CLSID_DEVICE_TORCH			= TEXT2CLSID("D_TORCH");
constexpr CLASS_ID CLSID_DEVICE_AF_MERGER		= TEXT2CLSID("D_AFMERG");
constexpr CLASS_ID CLSID_DEVICE_FLARE			= TEXT2CLSID("D_FLARE");

// Inventory items
constexpr CLASS_ID CLSID_IITEM_BOLT				= TEXT2CLSID("II_BOLT");

constexpr CLASS_ID CLSID_IITEM_MEDKIT			= TEXT2CLSID("II_MEDKI");
constexpr CLASS_ID CLSID_IITEM_BANDAGE			= TEXT2CLSID("II_BANDG");
constexpr CLASS_ID CLSID_IITEM_FOOD				= TEXT2CLSID("II_FOOD");
constexpr CLASS_ID CLSID_IITEM_BOTTLE			= TEXT2CLSID("II_BOTTL");
constexpr CLASS_ID CLSID_IITEM_ANTIRAD			= TEXT2CLSID("II_ANTIR");
constexpr CLASS_ID CLSID_IITEM_EXPLOSIVE		= TEXT2CLSID("II_EXPLO");

constexpr CLASS_ID CLSID_IITEM_BASIC			= TEXT2CLSID("II_BASIC");
constexpr CLASS_ID CLSID_IITEM_AMOUNTABLE		= TEXT2CLSID("II_AMTBL");
constexpr CLASS_ID CLSID_IITEM_CONTAINER		= TEXT2CLSID("II_CNTNR");
constexpr CLASS_ID CLSID_IITEM_ADDON			= TEXT2CLSID("II_ADDON");

// Info Document
constexpr CLASS_ID CLSID_IITEM_DOCUMENT			= TEXT2CLSID("II_DOC");

constexpr CLASS_ID CLSID_IITEM_ATTACH			= TEXT2CLSID("II_ATTCH");


// Grenades
constexpr CLASS_ID CLSID_GRENADE_F1				= TEXT2CLSID("G_F1");
constexpr CLASS_ID CLSID_OBJECT_G_RPG7			= TEXT2CLSID("G_RPG7");
constexpr CLASS_ID CLSID_GRENADE_RGD5			= TEXT2CLSID("G_RGD5");
constexpr CLASS_ID CLSID_OBJECT_G_FAKE			= TEXT2CLSID("G_FAKE");

//---------------------------------------------------------------------------------
constexpr CLASS_ID CLSID_OBJECT_PLAYERS_BAG		= TEXT2CLSID("MP_PLBAG");
//---------------------------------------------------------------------------------

// Equipment
constexpr CLASS_ID CLSID_EQUIPMENT_STALKER		= TEXT2CLSID("EQU_STLK");
constexpr CLASS_ID CLSID_EQUIPMENT_HELMET		= TEXT2CLSID("EQ_HLMET");
constexpr CLASS_ID CLSID_EQUIPMENT_BACKPACK		= TEXT2CLSID("EQ_BAKPK");

// Game types
constexpr CLASS_ID CLSID_SV_GAME_SINGLE				= TEXT2CLSID("SV_SINGL");
constexpr CLASS_ID CLSID_SV_GAME_DEATHMATCH			= TEXT2CLSID("SV_DM");
constexpr CLASS_ID CLSID_SV_GAME_TEAMDEATHMATCH		= TEXT2CLSID("SV_TDM");
constexpr CLASS_ID CLSID_SV_GAME_ARTEFACTHUNT		= TEXT2CLSID("SV_AHUNT");
constexpr CLASS_ID CLSID_SV_GAME_CAPTURETHEARTEFACT	= TEXT2CLSID("SV_CTA");
constexpr CLASS_ID CLSID_CL_GAME_SINGLE				= TEXT2CLSID("CL_SINGL");
constexpr CLASS_ID CLSID_CL_GAME_DEATHMATCH			= TEXT2CLSID("CL_DM");
constexpr CLASS_ID CLSID_CL_GAME_TEAMDEATHMATCH		= TEXT2CLSID("CL_TDM");
constexpr CLASS_ID CLSID_CL_GAME_ARTEFACTHUNT		= TEXT2CLSID("CL_AHUNT");
constexpr CLASS_ID CLSID_CL_GAME_CAPTURETHEARTEFACT	= TEXT2CLSID("CL_CTA");

// Game UI types
constexpr CLASS_ID CLSID_GAME_UI_SINGLE				= TEXT2CLSID("UI_SINGL");
constexpr CLASS_ID CLSID_GAME_UI_DEATHMATCH			= TEXT2CLSID("UI_DM");
constexpr CLASS_ID CLSID_GAME_UI_TEAMDEATHMATCH		= TEXT2CLSID("UI_TDM");
constexpr CLASS_ID CLSID_GAME_UI_ARTEFACTHUNT		= TEXT2CLSID("UI_AHUNT");
constexpr CLASS_ID CLSID_GAME_UI_CAPTURETHEARTEFACT	= TEXT2CLSID("UI_CTA");

constexpr CLASS_ID CLSID_ONLINE_OFFLINE_GROUP		= TEXT2CLSID("ON_OFF_G");
